// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: rpc.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SideEyeDemo_GetInfo_FullMethodName = "/rpcpb.SideEyeDemo/GetInfo"
)

// SideEyeDemoClient is the client API for SideEyeDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SideEyeDemoClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type sideEyeDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewSideEyeDemoClient(cc grpc.ClientConnInterface) SideEyeDemoClient {
	return &sideEyeDemoClient{cc}
}

func (c *sideEyeDemoClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, SideEyeDemo_GetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SideEyeDemoServer is the server API for SideEyeDemo service.
// All implementations must embed UnimplementedSideEyeDemoServer
// for forward compatibility
type SideEyeDemoServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	mustEmbedUnimplementedSideEyeDemoServer()
}

// UnimplementedSideEyeDemoServer must be embedded to have forward compatible implementations.
type UnimplementedSideEyeDemoServer struct {
}

func (UnimplementedSideEyeDemoServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedSideEyeDemoServer) mustEmbedUnimplementedSideEyeDemoServer() {}

// UnsafeSideEyeDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SideEyeDemoServer will
// result in compilation errors.
type UnsafeSideEyeDemoServer interface {
	mustEmbedUnimplementedSideEyeDemoServer()
}

func RegisterSideEyeDemoServer(s grpc.ServiceRegistrar, srv SideEyeDemoServer) {
	s.RegisterService(&SideEyeDemo_ServiceDesc, srv)
}

func _SideEyeDemo_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SideEyeDemoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SideEyeDemo_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SideEyeDemoServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SideEyeDemo_ServiceDesc is the grpc.ServiceDesc for SideEyeDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SideEyeDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.SideEyeDemo",
	HandlerType: (*SideEyeDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _SideEyeDemo_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
